#include <io/keyboard/keyboard.h>

const kb_layout_t kb_layout_en_us = {
    .physical = {
        [0x00 ... UINT16_MAX - 1] = 0xFFFF,

        [0x29] = KEY_BACKTICK,
        [0x02] = KEY_1,
        [0x03] = KEY_2,
        [0x04] = KEY_3,
        [0x05] = KEY_4,
        [0x06] = KEY_5,
        [0x07] = KEY_6,
        [0x08] = KEY_7,
        [0x09] = KEY_8,
        [0x0A] = KEY_9,
        [0x0B] = KEY_0,
        [0x0C] = KEY_MINUS,
        [0x0D] = KEY_EQUALS,
        [0x0E] = KEY_BACKSPACE,
        [0x0F] = KEY_TAB,
        [0x10] = KEY_Q,
        [0x11] = KEY_W,
        [0x12] = KEY_E,
        [0x13] = KEY_R,
        [0x14] = KEY_T,
        [0x15] = KEY_Y,
        [0x16] = KEY_U,
        [0x17] = KEY_I,
        [0x18] = KEY_O,
        [0x19] = KEY_P,
        [0x1A] = KEY_LEFT_BRACKET,
        [0x1B] = KEY_RIGHT_BRACKET,
        [0x1C] = KEY_ENTER,
        [0x3A] = KEY_CAPS_LOCK,
        [0x1E] = KEY_A,
        [0x1F] = KEY_S,
        [0x20] = KEY_D,
        [0x21] = KEY_F,
        [0x22] = KEY_G,
        [0x23] = KEY_H,
        [0x24] = KEY_J,
        [0x25] = KEY_K,
        [0x26] = KEY_L,
        [0x27] = KEY_SEMICOLON,
        [0x28] = KEY_APOSTROPHE,
        [0x2B] = KEY_BACKSLASH,
        [0x2A] = KEY_LEFT_SHIFT,
        [0x2C] = KEY_Z,
        [0x2D] = KEY_X,
        [0x2E] = KEY_C,
        [0x2F] = KEY_V,
        [0x30] = KEY_B,
        [0x31] = KEY_N,
        [0x32] = KEY_M,
        [0x33] = KEY_COMMA,
        [0x34] = KEY_PERIOD,
        [0x35] = KEY_FORWARD_SLASH,
        [0x36] = KEY_RIGHT_SHIFT,
        [0x1D] = KEY_LEFT_CONTROL,
        [0x38] = KEY_LEFT_ALT,
        [0x39] = KEY_SPACE,
        [0xE038] = KEY_RIGHT_ALT,
        [0xE01D] = KEY_RIGHT_CONTROL,
        [0xE048] = KEY_ARROW_UP,
        [0xE04B] = KEY_ARROW_LEFT,
        [0xE050] = KEY_ARROW_DOWN,
        [0xE04D] = KEY_ARROW_RIGHT,
    },
    .virtual = {
        [KEY_BACKTICK] = { .vk_normal = VK_BACKTICK, .vk_shift = VK_TILDE, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_1] = { .vk_normal = VK_1, .vk_shift = VK_EXCLAMATION_MARK, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_2] = { .vk_normal = VK_2, .vk_shift = VK_AT, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_3] = { .vk_normal = VK_3, .vk_shift = VK_HASH, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_4] = { .vk_normal = VK_4, .vk_shift = VK_DOLLAR, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_5] = { .vk_normal = VK_5, .vk_shift = VK_PERCENT, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_6] = { .vk_normal = VK_6, .vk_shift = VK_CARET, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_7] = { .vk_normal = VK_7, .vk_shift = VK_AMPERSAND, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_8] = { .vk_normal = VK_8, .vk_shift = VK_ASTERISK, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_9] = { .vk_normal = VK_9, .vk_shift = VK_LEFT_PARENTHESIS, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_0] = { .vk_normal = VK_0, .vk_shift = VK_RIGHT_PARENTHESIS, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_MINUS] = { .vk_normal = VK_MINUS, .vk_shift = VK_UNDERSCORE, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_EQUALS] = { .vk_normal = VK_EQUALS, .vk_shift = VK_PLUS, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_BACKSPACE] = { .vk_normal = VK_BACKSPACE, .vk_shift = VK_NONE, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_TAB] = { .vk_normal = VK_TAB, .vk_shift = VK_NONE, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_Q] = { .vk_normal = VK_q, .vk_shift = VK_Q, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_W] = { .vk_normal = VK_w, .vk_shift = VK_W, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_E] = { .vk_normal = VK_e, .vk_shift = VK_E, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_R] = { .vk_normal = VK_r, .vk_shift = VK_R, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_T] = { .vk_normal = VK_t, .vk_shift = VK_T, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_Y] = { .vk_normal = VK_y, .vk_shift = VK_Y, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_U] = { .vk_normal = VK_u, .vk_shift = VK_U, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_I] = { .vk_normal = VK_i, .vk_shift = VK_I, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_O] = { .vk_normal = VK_o, .vk_shift = VK_O, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_P] = { .vk_normal = VK_p, .vk_shift = VK_P, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_LEFT_BRACKET] = { .vk_normal = VK_LEFT_BRACKET, .vk_shift = VK_LEFT_BRACE },
        [KEY_RIGHT_BRACKET] = { .vk_normal = VK_RIGHT_BRACKET, .vk_shift = VK_RIGHT_BRACE },
        [KEY_ENTER] = { .vk_normal = VK_RETURN, .vk_shift = VK_NONE, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_CAPS_LOCK] = { .vk_normal = VK_CAPS_LOCK, .vk_shift = VK_NONE, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_A] = { .vk_normal = VK_a, .vk_shift = VK_A, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_S] = { .vk_normal = VK_s, .vk_shift = VK_S, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_D] = { .vk_normal = VK_d, .vk_shift = VK_D, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_F] = { .vk_normal = VK_f, .vk_shift = VK_F, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_G] = { .vk_normal = VK_g, .vk_shift = VK_G, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_H] = { .vk_normal = VK_h, .vk_shift = VK_H, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_J] = { .vk_normal = VK_j, .vk_shift = VK_J, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_K] = { .vk_normal = VK_k, .vk_shift = VK_K, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_L] = { .vk_normal = VK_l, .vk_shift = VK_L, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_SEMICOLON] = { .vk_normal = VK_SEMICOLON, .vk_shift = VK_COLON, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_APOSTROPHE] = { .vk_normal = VK_QUOTE, .vk_shift = VK_DOUBLE_QUOTE, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_BACKSLASH] = { .vk_normal = VK_BACKSLASH, .vk_shift = VK_PIPE },
        [KEY_LEFT_SHIFT] = { .vk_normal = VK_LEFT_SHIFT, .vk_shift = VK_LEFT_SHIFT, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_Z] = { .vk_normal = VK_z, .vk_shift = VK_Z, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_X] = { .vk_normal = VK_x, .vk_shift = VK_X, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_C] = { .vk_normal = VK_c, .vk_shift = VK_C, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_V] = { .vk_normal = VK_v, .vk_shift = VK_V, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_B] = { .vk_normal = VK_b, .vk_shift = VK_B, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_N] = { .vk_normal = VK_n, .vk_shift = VK_N, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_M] = { .vk_normal = VK_m, .vk_shift = VK_M, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_COMMA] = { .vk_normal = VK_COMMA, .vk_shift = VK_LESS_THAN, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_PERIOD] = { .vk_normal = VK_PERIOD, .vk_shift = VK_GREATER_THAN, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_FORWARD_SLASH] = { .vk_normal = VK_FORWARD_SLASH, .vk_shift = VK_QUESTION_MARK, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_RIGHT_SHIFT] = { .vk_normal = VK_RIGHT_SHIFT, .vk_shift = KEY_RIGHT_SHIFT, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_LEFT_CONTROL] = { .vk_normal = VK_LEFT_CONTROL, .vk_shift = VK_NONE, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_LEFT_ALT] = { .vk_normal = VK_LEFT_ALT, .vk_shift = VK_NONE, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_SPACE] = { .vk_normal = VK_SPACE, .vk_shift = VK_SPACE, .vk_altgr = VK_SPACE, .vk_shift_altgr = VK_SPACE },
        [KEY_RIGHT_ALT] = { .vk_normal = VK_RIGHT_ALT, .vk_shift = VK_NONE, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_RIGHT_CONTROL] = { .vk_normal = VK_RIGHT_CONTROL, .vk_shift = VK_NONE, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_ARROW_UP] = { .vk_normal = VK_ARROW_UP, .vk_shift = VK_NONE, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_ARROW_LEFT] = { .vk_normal = VK_ARROW_LEFT, .vk_shift = VK_NONE, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
        [KEY_ARROW_DOWN] = { .vk_normal = VK_ARROW_DOWN, .vk_shift = VK_NONE, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE},
        [KEY_ARROW_RIGHT] = { .vk_normal = VK_ARROW_RIGHT, .vk_shift = VK_NONE, .vk_altgr = VK_NONE, .vk_shift_altgr = VK_NONE },
    }
};
