#include <io/keyboard.h>

#define Altered(...) { [0 ... 3] = { .mods = 0xFF, .vk = UINT16_MAX }, [0] = __VA_ARGS__ }
#define AlteredNone() Altered({.mods = 0xFF, .vk = UINT16_MAX})

const kb_layout_t kb_layout_en_us = {
    [0x00 ... UINT16_MAX - 1] = { .physical = UINT16_MAX, .altered = AlteredNone() },

    [0x29] = { .physical = KEY_BACKTICK, .altered = Altered({ .mods = 0, .vk = VK_BACKTICK }, { .mods = VK_MOD_SHIFT, .vk = VK_TILDE }) },
    [0x02] = { .physical = KEY_1, .altered = Altered({ .mods = 0, .vk = VK_1 }, { .mods = VK_MOD_SHIFT, .vk = VK_EXCLAMATION_MARK }) },
    [0x03] = { .physical = KEY_2, .altered = Altered({ .mods = 0, .vk = VK_2 }, { .mods = VK_MOD_SHIFT, .vk = VK_AT }) },
    [0x04] = { .physical = KEY_3, .altered = Altered({ .mods = 0, .vk = VK_3 }, { .mods = VK_MOD_SHIFT, .vk = VK_HASH }) },
    [0x05] = { .physical = KEY_4, .altered = Altered({ .mods = 0, .vk = VK_4 }, { .mods = VK_MOD_SHIFT, .vk = VK_DOLLAR }) },
    [0x06] = { .physical = KEY_5, .altered = Altered({ .mods = 0, .vk = VK_5 }, { .mods = VK_MOD_SHIFT, .vk = VK_PERCENT }) },
    [0x07] = { .physical = KEY_6, .altered = Altered({ .mods = 0, .vk = VK_6 }, { .mods = VK_MOD_SHIFT, .vk = VK_CARET }) },
    [0x08] = { .physical = KEY_7, .altered = Altered({ .mods = 0, .vk = VK_7 }, { .mods = VK_MOD_SHIFT, .vk = VK_AMPERSAND }) },
    [0x09] = { .physical = KEY_8, .altered = Altered({ .mods = 0, .vk = VK_8 }, { .mods = VK_MOD_SHIFT, .vk = VK_ASTERISK }) },
    [0x0A] = { .physical = KEY_9, .altered = Altered({ .mods = 0, .vk = VK_9 }, { .mods = VK_MOD_SHIFT, .vk = VK_LEFT_PARENTHESIS }) },
    [0x0B] = { .physical = KEY_0, .altered = Altered({ .mods = 0, .vk = VK_0 }, { .mods = VK_MOD_SHIFT, .vk = VK_RIGHT_PARENTHESIS }) },
    [0x0C] = { .physical = KEY_MINUS, .altered = Altered({ .mods = 0, .vk = VK_MINUS }, { .mods = VK_MOD_SHIFT, .vk = VK_UNDERSCORE }) },
    [0x0D] = { .physical = KEY_EQUALS, .altered = Altered({ .mods = 0, .vk = VK_EQUALS }, { .mods = VK_MOD_SHIFT, .vk = VK_PLUS }) },
    [0x0E] = { .physical = KEY_BACKSPACE, .altered = Altered({ .mods = VK_MOD_IGNORE, .vk = VK_BACKSPACE }) },

    [0x0F] = { .physical = KEY_TAB, .altered = Altered({ .mods = VK_MOD_IGNORE, .vk = VK_TAB }) },
    [0x10] = { .physical = KEY_Q, .altered = Altered({ .mods = 0, .vk = VK_q }, { .mods = VK_MOD_SHIFT, .vk = VK_Q }) },
    [0x11] = { .physical = KEY_W, .altered = Altered({ .mods = 0, .vk = VK_w }, { .mods = VK_MOD_SHIFT, .vk = VK_W }) },
    [0x12] = { .physical = KEY_E, .altered = Altered({ .mods = 0, .vk = VK_e }, { .mods = VK_MOD_SHIFT, .vk = VK_E }) },
    [0x13] = { .physical = KEY_R, .altered = Altered({ .mods = 0, .vk = VK_r }, { .mods = VK_MOD_SHIFT, .vk = VK_R }) },
    [0x14] = { .physical = KEY_T, .altered = Altered({ .mods = 0, .vk = VK_t }, { .mods = VK_MOD_SHIFT, .vk = VK_T }) },
    [0x15] = { .physical = KEY_Y, .altered = Altered({ .mods = 0, .vk = VK_y }, { .mods = VK_MOD_SHIFT, .vk = VK_Y }) },
    [0x16] = { .physical = KEY_U, .altered = Altered({ .mods = 0, .vk = VK_u }, { .mods = VK_MOD_SHIFT, .vk = VK_U }) },
    [0x17] = { .physical = KEY_I, .altered = Altered({ .mods = 0, .vk = VK_i }, { .mods = VK_MOD_SHIFT, .vk = VK_I }) },
    [0x18] = { .physical = KEY_O, .altered = Altered({ .mods = 0, .vk = VK_o }, { .mods = VK_MOD_SHIFT, .vk = VK_O }) },
    [0x19] = { .physical = KEY_P, .altered = Altered({ .mods = 0, .vk = VK_p }, { .mods = VK_MOD_SHIFT, .vk = VK_P }) },
    [0x1A] = { .physical = KEY_LEFT_BRACKET, .altered = Altered({ .mods = 0, .vk = VK_LEFT_BRACKET }, { .mods = VK_MOD_SHIFT, .vk = VK_LEFT_BRACE }) },
    [0x1B] = { .physical = KEY_RIGHT_BRACKET, .altered = Altered({ .mods = 0, .vk = VK_RIGHT_BRACKET }, { .mods = VK_MOD_SHIFT, .vk = VK_RIGHT_BRACE }) },
    [0x2B] = { .physical = KEY_BACKSLASH, .altered = Altered({ .mods = 0, .vk = VK_BACKSLASH }, { .mods = VK_MOD_SHIFT, .vk = VK_PIPE }) },

    [0x3A] = { .physical = KEY_CAPS_LOCK, .altered = Altered({ .mods = VK_MOD_IGNORE, .vk = VK_CAPS_LOCK }) },
    [0x1E] = { .physical = KEY_A, .altered = Altered({ .mods = 0, .vk = VK_a }, { .mods = VK_MOD_SHIFT, .vk = VK_A }) },
    [0x1F] = { .physical = KEY_S, .altered = Altered({ .mods = 0, .vk = VK_s }, { .mods = VK_MOD_SHIFT, .vk = VK_S }) },
    [0x20] = { .physical = KEY_D, .altered = Altered({ .mods = 0, .vk = VK_d }, { .mods = VK_MOD_SHIFT, .vk = VK_D }) },
    [0x21] = { .physical = KEY_F, .altered = Altered({ .mods = 0, .vk = VK_f }, { .mods = VK_MOD_SHIFT, .vk = VK_F }) },
    [0x22] = { .physical = KEY_G, .altered = Altered({ .mods = 0, .vk = VK_g }, { .mods = VK_MOD_SHIFT, .vk = VK_G }) },
    [0x23] = { .physical = KEY_H, .altered = Altered({ .mods = 0, .vk = VK_h }, { .mods = VK_MOD_SHIFT, .vk = VK_H }) },
    [0x24] = { .physical = KEY_J, .altered = Altered({ .mods = 0, .vk = VK_j }, { .mods = VK_MOD_SHIFT, .vk = VK_J }) },
    [0x25] = { .physical = KEY_K, .altered = Altered({ .mods = 0, .vk = VK_k }, { .mods = VK_MOD_SHIFT, .vk = VK_K }) },
    [0x26] = { .physical = KEY_L, .altered = Altered({ .mods = 0, .vk = VK_l }, { .mods = VK_MOD_SHIFT, .vk = VK_L }) },
    [0x27] = { .physical = KEY_SEMICOLON, .altered = Altered({ .mods = 0, .vk = VK_SEMICOLON }, { .mods = VK_MOD_SHIFT, .vk = VK_COLON }) },
    [0x28] = { .physical = KEY_APOSTROPHE, .altered = Altered({ .mods = 0, .vk = VK_QUOTE }, { .mods = VK_MOD_SHIFT, .vk = VK_DOUBLE_QUOTE }) },
    [0x1C] = { .physical = KEY_ENTER, .altered = Altered({ .mods = VK_MOD_IGNORE, .vk = VK_RETURN }) },

    [0x2A] = { .physical = KEY_LEFT_SHIFT , .altered = Altered({ .mods = VK_MOD_IGNORE, .vk = VK_LEFT_SHIFT }) },
    [0x2C] = { .physical = KEY_Z, .altered = Altered({ .mods = 0, .vk = VK_z }, { .mods = VK_MOD_SHIFT, .vk = VK_Z }) },
    [0x2D] = { .physical = KEY_X, .altered = Altered({ .mods = 0, .vk = VK_x }, { .mods = VK_MOD_SHIFT, .vk = VK_X }) },
    [0x2E] = { .physical = KEY_C, .altered = Altered({ .mods = 0, .vk = VK_c }, { .mods = VK_MOD_SHIFT, .vk = VK_C }) },
    [0x2F] = { .physical = KEY_V, .altered = Altered({ .mods = 0, .vk = VK_v }, { .mods = VK_MOD_SHIFT, .vk = VK_V }) },
    [0x30] = { .physical = KEY_B, .altered = Altered({ .mods = 0, .vk = VK_b }, { .mods = VK_MOD_SHIFT, .vk = VK_B }) },
    [0x31] = { .physical = KEY_N, .altered = Altered({ .mods = 0, .vk = VK_n }, { .mods = VK_MOD_SHIFT, .vk = VK_N }) },
    [0x32] = { .physical = KEY_M, .altered = Altered({ .mods = 0, .vk = VK_m }, { .mods = VK_MOD_SHIFT, .vk = VK_M }) },
    [0x33] = { .physical = KEY_COMMA, .altered = Altered({ .mods = 0, .vk = VK_COMMA }, { .mods = VK_MOD_SHIFT, .vk = VK_LESS_THAN }) },
    [0x34] = { .physical = KEY_PERIOD, .altered = Altered({ .mods = 0, .vk = VK_PERIOD }, { .mods = VK_MOD_SHIFT, .vk = VK_GREATER_THAN }) },
    [0x35] = { .physical = KEY_FORWARD_SLASH, .altered = Altered({ .mods = 0, .vk = VK_FORWARD_SLASH }, { .mods = VK_MOD_SHIFT, .vk = VK_QUESTION_MARK }) },
    [0x36] = { .physical = KEY_RIGHT_SHIFT, .altered = Altered({ .mods = VK_MOD_IGNORE, .vk = VK_RIGHT_SHIFT }) },
    
    [0x1D] = { .physical = KEY_LEFT_CONTROL, .altered = Altered({ .mods = VK_MOD_IGNORE, .vk = VK_LEFT_CONTROL }) },
    [0x38] = { .physical = KEY_LEFT_ALT, .altered = Altered({ .mods = VK_MOD_IGNORE, .vk = VK_LEFT_ALT }) },
    [0x39] = { .physical = KEY_SPACE, .altered = Altered({ .mods = VK_MOD_IGNORE, .vk = VK_SPACE }) },
    [0xE038] = { .physical = KEY_RIGHT_ALT, .altered = Altered({ .mods = VK_MOD_IGNORE, .vk = VK_RIGHT_ALT }) },
    [0xE01D] = { .physical = KEY_RIGHT_CONTROL, .altered = Altered({ .mods = VK_MOD_IGNORE, .vk = VK_RIGHT_CONTROL }) },

    [0xE048] = { .physical = KEY_ARROW_UP, .altered = Altered({ .mods = VK_MOD_IGNORE, .vk = VK_ARROW_UP}) },
    [0xE04B] = { .physical = KEY_ARROW_LEFT, .altered = Altered({ .mods = VK_MOD_IGNORE, .vk = VK_ARROW_LEFT}) },
    [0xE050] = { .physical = KEY_ARROW_DOWN, .altered = Altered({ .mods = VK_MOD_IGNORE, .vk = VK_ARROW_DOWN}) },
    [0xE04D] = { .physical = KEY_ARROW_RIGHT, .altered = Altered({ .mods = VK_MOD_IGNORE, .vk = VK_ARROW_RIGHT}) },
};
