#pragma once

#define KEY_BACKTICK         0x00
#define KEY_1                0x01
#define KEY_2                0x02
#define KEY_3                0x03
#define KEY_4                0x04
#define KEY_5                0x05
#define KEY_6                0x06
#define KEY_7                0x07
#define KEY_8                0x08
#define KEY_9                0x09
#define KEY_0                0x0A
#define KEY_MINUS            0x0B
#define KEY_EQUALS           0x0C
#define KEY_BACKSPACE        0x0E
#define KEY_TAB              0x0F
#define KEY_Q                0x10
#define KEY_W                0x11
#define KEY_E                0x12
#define KEY_R                0x13
#define KEY_T                0x14
#define KEY_Y                0x15
#define KEY_U                0x16
#define KEY_I                0x17
#define KEY_O                0x18
#define KEY_P                0x19
#define KEY_LEFT_BRACKET     0x1A
#define KEY_RIGHT_BRACKET    0x1B
#define KEY_ENTER            0x1C
#define KEY_CAPS_LOCK        0x1D
#define KEY_A                0x1E
#define KEY_S                0x1F
#define KEY_D                0x20
#define KEY_F                0x21
#define KEY_G                0x22
#define KEY_H                0x23
#define KEY_J                0x24
#define KEY_K                0x25
#define KEY_L                0x26
#define KEY_SEMICOLON        0x27
#define KEY_APOSTROPHE       0x28
#define KEY_BACKSLASH        0x29
#define KEY_LEFT_SHIFT       0x2A
#define KEY_Z                0x2C
#define KEY_X                0x2D
#define KEY_C                0x2E
#define KEY_V                0x2F
#define KEY_B                0x30
#define KEY_N                0x31
#define KEY_M                0x32
#define KEY_COMMA            0x33
#define KEY_PERIOD           0x34
#define KEY_FORWARD_SLASH    0x35
#define KEY_RIGHT_SHIFT      0x36
#define KEY_LEFT_CONTROL     0x37
#define KEY_LEFT_ALT         0x38
#define KEY_SPACE            0x39
#define KEY_RIGHT_ALT        0x3A
#define KEY_RIGHT_CONTROL    0x3B
#define KEY_ARROW_UP         0x3C
#define KEY_ARROW_LEFT       0x3D
#define KEY_ARROW_DOWN       0x3E
#define KEY_ARROW_RIGHT      0x3F

#define VK_BACKTICK          '`'
#define VK_TILDE             '~'
#define VK_1                 '1'
#define VK_EXCLAMATION_MARK  '!'
#define VK_2                 '2'
#define VK_AT                '@'
#define VK_3                 '3'
#define VK_HASH              '#'
#define VK_4                 '4'
#define VK_DOLLAR            '$'
#define VK_5                 '5'
#define VK_PERCENT           '%'
#define VK_6                 '6'
#define VK_CARET             '^'
#define VK_7                 '7'
#define VK_AMPERSAND         '&'
#define VK_8                 '8'
#define VK_ASTERISK          '*'
#define VK_9                 '9'
#define VK_LEFT_PARENTHESIS  '('
#define VK_0                 '0'
#define VK_RIGHT_PARENTHESIS ')'
#define VK_MINUS             '-'
#define VK_UNDERSCORE        '_'
#define VK_EQUALS            '='
#define VK_PLUS              '+'
#define VK_BACKSPACE         '\b'
#define VK_TAB               '\t'
#define VK_q                 'q'
#define VK_Q                 'Q'
#define VK_w                 'w'
#define VK_W                 'W'
#define VK_e                 'e'
#define VK_E                 'E'
#define VK_r                 'r'
#define VK_R                 'R'
#define VK_t                 't'
#define VK_T                 'T'
#define VK_y                 'y'
#define VK_Y                 'Y'
#define VK_u                 'u'
#define VK_U                 'U'
#define VK_i                 'i'
#define VK_I                 'I'
#define VK_o                 'o'
#define VK_O                 'O'
#define VK_p                 'p'
#define VK_P                 'P'
#define VK_LEFT_BRACKET      '['
#define VK_LEFT_BRACE        '{'
#define VK_RIGHT_BRACKET     ']'
#define VK_RIGHT_BRACE       '}'
#define VK_BACKSLASH         '\\'
#define VK_PIPE              '|'
#define VK_CAPS_LOCK         0xFF00
#define VK_a                 'a'
#define VK_A                 'A'
#define VK_s                 's'
#define VK_S                 'S'
#define VK_d                 'd'
#define VK_D                 'D'
#define VK_f                 'f'
#define VK_F                 'F'
#define VK_g                 'g'
#define VK_G                 'G'
#define VK_h                 'h'
#define VK_H                 'H'
#define VK_j                 'j'
#define VK_J                 'J'
#define VK_k                 'k'
#define VK_K                 'K'
#define VK_l                 'l'
#define VK_L                 'L'
#define VK_SEMICOLON         ';'
#define VK_COLON             ':'
#define VK_QUOTE             '\''
#define VK_DOUBLE_QUOTE      '"'
#define VK_RETURN            '\n'
#define VK_LEFT_SHIFT        0xFF01
#define VK_z                 'z'
#define VK_Z                 'Z'
#define VK_x                 'x'
#define VK_X                 'X'
#define VK_c                 'c'
#define VK_C                 'C'
#define VK_v                 'v'
#define VK_V                 'V'
#define VK_b                 'b'
#define VK_B                 'B'
#define VK_n                 'n'
#define VK_N                 'N'
#define VK_m                 'm'
#define VK_M                 'M'
#define VK_COMMA             ','
#define VK_LESS_THAN         '<'
#define VK_PERIOD            '.'
#define VK_GREATER_THAN      '>'
#define VK_FORWARD_SLASH     '/'
#define VK_QUESTION_MARK     '?'
#define VK_RIGHT_SHIFT       0xFF02
#define VK_LEFT_CONTROL      0xFF03
#define VK_LEFT_ALT          0xFF04
#define VK_SPACE             ' '
#define VK_RIGHT_ALT         0xFF05
#define VK_RIGHT_CONTROL     0xFF06
#define VK_ARROW_UP          0xFF07
#define VK_ARROW_LEFT        0xFF08
#define VK_ARROW_DOWN        0xFF09
#define VK_ARROW_RIGHT       0xFF0A

#define VK_NONE 0xFFFF
 