#pragma once

#include <device/keyboard/vk_layout.h>

// Single scancode pressed
#define KEY_PRESSED_ESCAPE                  0x01
#define KEY_PRESSED_1                       0x02
#define KEY_PRESSED_2                       0x03
#define KEY_PRESSED_3                       0x04
#define KEY_PRESSED_4                       0x05
#define KEY_PRESSED_5                       0x06
#define KEY_PRESSED_6                       0x07
#define KEY_PRESSED_7                       0x08
#define KEY_PRESSED_8                       0x09
#define KEY_PRESSED_9                       0x0A
#define KEY_PRESSED_0                       0x0B
#define KEY_PRESSED_MINUS                   0x0C
#define KEY_PRESSED_EQUALS                  0x0D
#define KEY_PRESSED_BACKSPACE               0x0E
#define KEY_PRESSED_TAB                     0x0F
#define KEY_PRESSED_Q                       0x10
#define KEY_PRESSED_W                       0x11
#define KEY_PRESSED_E                       0x12
#define KEY_PRESSED_R                       0x13
#define KEY_PRESSED_T                       0x14
#define KEY_PRESSED_Y                       0x15
#define KEY_PRESSED_U                       0x16
#define KEY_PRESSED_I                       0x17
#define KEY_PRESSED_O                       0x18
#define KEY_PRESSED_P                       0x19
#define KEY_PRESSED_OPEN_SQUARE_BRACKET     0x1A
#define KEY_PRESSED_CLOSE_SQUARE_BRACKET    0x1B
#define KEY_PRESSED_ENTER                   0x1C
#define KEY_PRESSED_LEFT_CTRL               0x1D
#define KEY_PRESSED_A                       0x1E
#define KEY_PRESSED_S                       0x1F
#define KEY_PRESSED_D                       0x20
#define KEY_PRESSED_F                       0x21
#define KEY_PRESSED_G                       0x22
#define KEY_PRESSED_H                       0x23
#define KEY_PRESSED_J                       0x24
#define KEY_PRESSED_K                       0x25
#define KEY_PRESSED_L                       0x26
#define KEY_PRESSED_SEMICOLON               0x27
#define KEY_PRESSED_SINGLE_QUOTE            0x28
#define KEY_PRESSED_BACK_TICK               0x29
#define KEY_PRESSED_LEFT_SHIFT              0x2A
#define KEY_PRESSED_BACK_SLASH              0x2B
#define KEY_PRESSED_Z                       0x2C
#define KEY_PRESSED_X                       0x2D
#define KEY_PRESSED_C                       0x2E
#define KEY_PRESSED_V                       0x2F
#define KEY_PRESSED_B                       0x30
#define KEY_PRESSED_N                       0x31
#define KEY_PRESSED_M                       0x32
#define KEY_PRESSED_COMMA                   0x33
#define KEY_PRESSED_PERIOD                  0x34
#define KEY_PRESSED_FORWARD_SLASH           0x35
#define KEY_PRESSED_RIGHT_SHIFT             0x36
#define KEY_PRESSED_KEYPAD_ASTERISK         0x37
#define KEY_PRESSED_LEFT_ALT                0x38
#define KEY_PRESSED_SPACE                   0x39
#define KEY_PRESSED_CAPS_LOCK               0x3A
#define KEY_PRESSED_F1                      0x3B
#define KEY_PRESSED_F2                      0x3C
#define KEY_PRESSED_F3                      0x3D
#define KEY_PRESSED_F4                      0x3E
#define KEY_PRESSED_F5                      0x3F
#define KEY_PRESSED_F6                      0x40
#define KEY_PRESSED_F7                      0x41
#define KEY_PRESSED_F8                      0x42
#define KEY_PRESSED_F9                      0x43
#define KEY_PRESSED_F10                     0x44
#define KEY_PRESSED_NUMBER_LOCK             0x45
#define KEY_PRESSED_SCROLL_LOCK             0x46
#define KEY_PRESSED_KEYPAD_7                0x47
#define KEY_PRESSED_KEYPAD_8                0x48
#define KEY_PRESSED_KEYPAD_9                0x49
#define KEY_PRESSED_KEYPAD_MINUS            0x4A
#define KEY_PRESSED_KEYPAD_4                0x4B
#define KEY_PRESSED_KEYPAD_5                0x4C
#define KEY_PRESSED_KEYPAD_6                0x4D
#define KEY_PRESSED_KEYPAD_PLUS             0x4E
#define KEY_PRESSED_KEYPAD_1                0x4F
#define KEY_PRESSED_KEYPAD_2                0x50
#define KEY_PRESSED_KEYPAD_3                0x51
#define KEY_PRESSED_KEYPAD_0                0x52
#define KEY_PRESSED_KEYPAD_PERIOD           0x53
#define KEY_PRESSED_F11                     0x57
#define KEY_PRESSED_F12                     0x58

// Single scancode released
#define KEY_RELEASED_ESCAPE                 0x81
#define KEY_RELEASED_1                      0x82
#define KEY_RELEASED_2                      0x83
#define KEY_RELEASED_3                      0x84
#define KEY_RELEASED_4                      0x85
#define KEY_RELEASED_5                      0x86
#define KEY_RELEASED_6                      0x87
#define KEY_RELEASED_7                      0x88
#define KEY_RELEASED_8                      0x89
#define KEY_RELEASED_9                      0x8A
#define KEY_RELEASED_0                      0x8B
#define KEY_RELEASED_MINUS                  0x8C
#define KEY_RELEASED_EQUALS                 0x8D
#define KEY_RELEASED_BACKSPACE              0x8E
#define KEY_RELEASED_TAB                    0x8F
#define KEY_RELEASED_Q                      0x90
#define KEY_RELEASED_W                      0x91
#define KEY_RELEASED_E                      0x92
#define KEY_RELEASED_R                      0x93
#define KEY_RELEASED_T                      0x94
#define KEY_RELEASED_Y                      0x95
#define KEY_RELEASED_U                      0x96
#define KEY_RELEASED_I                      0x97
#define KEY_RELEASED_O                      0x98
#define KEY_RELEASED_P                      0x99
#define KEY_RELEASED_OPEN_SQUARE_BRACKET    0x9A
#define KEY_RELEASED_CLOSE_SQUARE_BRACKET   0x9B
#define KEY_RELEASED_ENTER                  0x9C
#define KEY_RELEASED_LEFT_CTRL              0x9D
#define KEY_RELEASED_A                      0x9E
#define KEY_RELEASED_S                      0x9F
#define KEY_RELEASED_D                      0xA0
#define KEY_RELEASED_F                      0xA1
#define KEY_RELEASED_G                      0xA2
#define KEY_RELEASED_H                      0xA3
#define KEY_RELEASED_J                      0xA4
#define KEY_RELEASED_K                      0xA5
#define KEY_RELEASED_L                      0xA6
#define KEY_RELEASED_SEMICOLON              0xA7
#define KEY_RELEASED_SINGLE_QUOTE           0xA8
#define KEY_RELEASED_BACK_TICK              0xA9
#define KEY_RELEASED_LEFT_SHIFT             0xAA
#define KEY_RELEASED_BACK_SLASH             0xAB
#define KEY_RELEASED_Z                      0xAC
#define KEY_RELEASED_X                      0xAD
#define KEY_RELEASED_C                      0xAE
#define KEY_RELEASED_V                      0xAF
#define KEY_RELEASED_B                      0xB0
#define KEY_RELEASED_N                      0xB1
#define KEY_RELEASED_M                      0xB2
#define KEY_RELEASED_COMMA                  0xB3
#define KEY_RELEASED_PERIOD                 0xB4
#define KEY_RELEASED_FORWARD_SLASH          0xB5
#define KEY_RELEASED_RIGHT_SHIFT            0xB6
#define KEY_RELEASED_KEYPAD_ASTERISK        0xB7
#define KEY_RELEASED_LEFT_ALT               0xB8
#define KEY_RELEASED_SPACE                  0xB9
#define KEY_RELEASED_CAPS_LOCK              0xBA
#define KEY_RELEASED_F1                     0xBB
#define KEY_RELEASED_F2                     0xBC
#define KEY_RELEASED_F3                     0xBD
#define KEY_RELEASED_F4                     0xBE
#define KEY_RELEASED_F5                     0xBF
#define KEY_RELEASED_F6                     0xC0
#define KEY_RELEASED_F7                     0xC1
#define KEY_RELEASED_F8                     0xC2
#define KEY_RELEASED_F9                     0xC3
#define KEY_RELEASED_F10                    0xC4
#define KEY_RELEASED_NUMBER_LOCK            0xC5
#define KEY_RELEASED_SCROLL_LOCK            0xC6
#define KEY_RELEASED_KEYPAD_7               0xC7
#define KEY_RELEASED_KEYPAD_8               0xC8
#define KEY_RELEASED_KEYPAD_9               0xC9
#define KEY_RELEASED_KEYPAD_MINUS           0xCA
#define KEY_RELEASED_KEYPAD_4               0xCB
#define KEY_RELEASED_KEYPAD_5               0xCC
#define KEY_RELEASED_KEYPAD_6               0xCD
#define KEY_RELEASED_KEYPAD_PLUS            0xCE
#define KEY_RELEASED_KEYPAD_1               0xCF
#define KEY_RELEASED_KEYPAD_2               0xD0
#define KEY_RELEASED_KEYPAD_3               0xD1
#define KEY_RELEASED_KEYPAD_0               0xD2
#define KEY_RELEASED_KEYPAD_PERIOD          0xD3
#define KEY_RELEASED_F11                    0xD7
#define KEY_RELEASED_F12                    0xD8

// Multi scancode pressed
#define KEY_PRESSED_KEYPAD_ENTER            0xE01C
#define KEY_PRESSED_RIGHT_CTRL              0xE01D
#define KEY_PRESSED_KEYPAD_FORWARD_SLASH    0xE035
#define KEY_PRESSED_RIGHT_ALT               0xE038
#define KEY_PRESSED_HOME                    0xE047
#define KEY_PRESSED_ARROW_UP                0xE048
#define KEY_PRESSED_PAGE_UP                 0xE049
#define KEY_PRESSED_ARROW_LEFT              0xE04B
#define KEY_PRESSED_ARROW_RIGHT             0xE04D
#define KEY_PRESSED_END                     0xE04F
#define KEY_PRESSED_ARROW_DOWN              0xE050
#define KEY_PRESSED_PAGE_DOWN               0xE051
#define KEY_PRESSED_INSERT                  0xE052
#define KEY_PRESSED_DELETE                  0xE053
#define KEY_PRESSED_LEFT_GUI                0xE05B
#define KEY_PRESSED_RIGHT_GUI               0xE05C
#define KEY_PRESSED_MENU                    0xE05D

// Multi scancode released
#define KEY_RELEASED_KEYPAD_ENTER            0xE09C
#define KEY_RELEASED_RIGHT_CTRL              0xE09D
#define KEY_RELEASED_KEYPAD_FORWARD_SLASH    0xE0B5
#define KEY_RELEASED_RIGHT_ALT               0xE0B8
#define KEY_RELEASED_HOME                    0xE0C7
#define KEY_RELEASED_ARROW_UP                0xE0C8
#define KEY_RELEASED_PAGE_UP                 0xE0C9
#define KEY_RELEASED_ARROW_LEFT              0xE0CB
#define KEY_RELEASED_ARROW_RIGHT             0xE0CD
#define KEY_RELEASED_END                     0xE0CF
#define KEY_RELEASED_ARROW_DOWN              0xE0D0
#define KEY_RELEASED_PAGE_DOWN               0xE0D1
#define KEY_RELEASED_INSERT                  0xE0D2
#define KEY_RELEASED_DELETE                  0xE0D3
#define KEY_RELEASED_LEFT_GUI                0xE0DB
#define KEY_RELEASED_RIGHT_GUI               0xE0DC
#define KEY_RELEASED_MENU                    0xE0DD

#ifdef __cplusplus
extern "C"
#endif
key_state_t physical_to_virtual_key(uint16_t physical);
uint8_t virtual_key_apply_modifiers(uint8_t vk, keyboard_state_t keyboardState);